ALTER TABLE "Evidence"
ALTER COLUMN "fileUrl" DROP NOT NULL,
ALTER COLUMN "originalFileName" DROP NOT NULL,
ALTER COLUMN "storedFileName" DROP NOT NULL,
ALTER COLUMN "mimeType" DROP NOT NULL,
ALTER COLUMN "fileSize" DROP NOT NULL;

ALTER TABLE "Evidence"
ADD COLUMN "submittedText" TEXT;
