/**
 * This file defines the root layout for the TimeLend frontend.
 * It exists to wrap every page with global metadata and styles.
 * It fits the system by establishing the shell that future screens will inherit.
 */
import type { Metadata } from "next";
import type { ReactNode } from "react";
import { Manrope, Space_Grotesk } from "next/font/google";
import { cookies } from "next/headers";
import { ShieldCheck } from "lucide-react";
import { siGithub, siX } from "simple-icons";

import { AppProviders } from "@/components/app-providers";
import { SiteNavigation } from "@/components/site-navigation";
import {
  defaultLanguage,
  languageCookieName,
  resolveLanguage,
  translations,
} from "@/lib/i18n/translations";
import { siteConfig } from "@/lib/site-config";
import { cn } from "@/lib/utils";

import "./globals.css";

/**
 * This metadata object describes the application for browsers and platforms.
 * It receives no runtime input.
 * It returns static metadata consumed by Next.js.
 * It is important because it sets the default identity of the frontend shell.
 */
export const metadata: Metadata = {
  title: "TimeLend",
  description: "Premium TimeLend demo for wallet auth, on-chain commitments, and AI verification.",
  icons: {
    icon: "/logo.png",
  },
};

const bodyFont = Manrope({
  subsets: ["latin"],
  variable: "--font-body",
});

const displayFont = Space_Grotesk({
  subsets: ["latin"],
  variable: "--font-display",
});

type RootLayoutProps = {
  children: ReactNode;
};

type SocialIconProps = {
  icon: {
    path: string;
  };
};

const linkedinSimpleIcon = {
  path: "M20.447 20.452h-3.554v-5.569c0-1.328-.027-3.037-1.852-3.037-1.853 0-2.136 1.445-2.136 2.939v5.667H9.351V9h3.414v1.561h.046c.477-.9 1.637-1.85 3.37-1.85 3.601 0 4.267 2.37 4.267 5.455v6.286zM5.337 7.433c-1.144 0-2.063-.926-2.063-2.065 0-1.138.92-2.063 2.063-2.063 1.14 0 2.064.925 2.064 2.063 0 1.139-.925 2.065-2.064 2.065zm1.782 13.019H3.555V9h3.564v11.452zM22.225 0H1.771C.792 0 0 .774 0 1.729v20.542C0 23.227.792 24 1.771 24h20.451C23.2 24 24 23.227 24 22.271V1.729C24 .774 23.2 0 22.222 0h.003z",
};

function SocialIcon({ icon }: SocialIconProps) {
  return (
    <svg
      aria-hidden="true"
      className="size-4 shrink-0"
      fill="currentColor"
      viewBox="0 0 24 24"
    >
      <path d={icon.path} />
    </svg>
  );
}

/**
 * This component renders the root HTML layout for every page.
 * It receives the page content generated by nested routes.
 * It returns the shared HTML and body structure.
 * It is important because it centralizes global wrappers and styles.
 */
export default async function RootLayout({ children }: RootLayoutProps) {
  const cookieStore = await cookies();
  const initialLanguage = resolveLanguage(
    cookieStore.get(languageCookieName)?.value ?? defaultLanguage,
  );
  const dictionary = translations[initialLanguage];

  return (
    <html lang={initialLanguage}>
      <body className={cn("app-shell", bodyFont.variable, displayFont.variable)}>
        <AppProviders initialLanguage={initialLanguage}>
          <div className="mx-auto flex min-h-screen w-full max-w-[1440px] flex-col px-4 pb-8 sm:px-6 lg:px-8">
            <SiteNavigation />
            <div className="flex-1">{children}</div>

            <footer className="glass-noise mt-10 grid gap-6 rounded-2xl border border-white/10 bg-slate-950/45 px-6 py-6 shadow-[0_24px_80px_-32px_rgba(2,6,23,0.92)] backdrop-blur-xl">
              <div className="flex flex-col items-center gap-4 text-center">
                <div className="flex items-center gap-3">
                  <div className="flex size-10 items-center justify-center rounded-2xl border border-emerald-300/16 bg-emerald-400/10 text-emerald-100">
                    <ShieldCheck className="size-5" />
                  </div>
                  <div>
                    <p className="section-eyebrow">{siteConfig.name}</p>
                    <p className="font-display text-lg font-semibold tracking-tight text-white">
                      {dictionary.footerProductionSurface}
                    </p>
                  </div>
                </div>

                <p className="max-w-2xl text-sm leading-6 text-slate-300/72">
                  {dictionary.footerDescription}
                </p>

                <p className="text-sm text-slate-400">{dictionary.footerBuiltBy}</p>
              </div>

              <div
                aria-label={dictionary.communityLinks}
                className="flex flex-wrap items-center justify-center gap-x-5 gap-y-3 border-t border-white/8 pt-5"
              >
                <a
                  className="inline-flex items-center gap-2 text-sm text-slate-400 transition-colors hover:text-white"
                  href="https://x.com/santidandreaa"
                  rel="noreferrer"
                  target="_blank"
                >
                  <SocialIcon icon={siX} />
                  <span>X</span>
                </a>

                <a
                  className="inline-flex items-center gap-2 text-sm text-slate-400 transition-colors hover:text-white"
                  href="https://github.com/Santid04"
                  rel="noreferrer"
                  target="_blank"
                >
                  <SocialIcon icon={siGithub} />
                  <span>GitHub</span>
                </a>

                <a
                  className="inline-flex items-center gap-2 text-sm text-slate-400 transition-colors hover:text-white"
                  href="https://www.linkedin.com/in/santiagodandrea-it/"
                  rel="noreferrer"
                  target="_blank"
                >
                  <SocialIcon icon={linkedinSimpleIcon} />
                  <span>LinkedIn</span>
                </a>
              </div>
            </footer>
          </div>
        </AppProviders>
      </body>
    </html>
  );
}
