/**
 * This file exposes shared metadata for the repository-owned contract artifacts.
 * It exists so frontend and backend code can rely on one canonical artifact naming convention.
 * It fits the system by keeping blockchain asset discovery centralized inside the shared package.
 */
/**
 * This constant maps contract identifiers to the shared ABI files generated by the smart contract workspace.
 * It receives no runtime input and is loaded statically.
 * It returns a small contract-to-artifact path registry.
 * It is important because later integrations should not hardcode artifact paths ad hoc.
 */
export const sharedContractArtifacts = {
  TimeLend: "shared/abi/TimeLend.json"
} as const;
